name: pro_z
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  intl: ^0.18.1
  flutter_screenutil: ^5.8.4
  video_player: ^2.6.1
  fluttertoast: ^8.2.2
  flutter_expandable_fab: ^1.8.1
  shared_preferences: ^2.1.1
  streaming_shared_preferences: ^2.0.0
  cloud_firestore: ^4.8.0
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^14.1.1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.0
  http: ^0.13.6
  dio: ^5.2.0
  pretty_dio_logger: ^1.3.1
  cookie_jar: ^4.0.3
  dio_cookie_manager: ^3.1.0
  firebase_auth: ^4.6.2
  flutter_facebook_auth: ^5.0.11
  google_sign_in: ^6.1.3
  pinput: ^2.2.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/


